# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "src"
  t.test_files = FileList["test/**/*_test.rb"]
end

task default: %i[test steep steep_cli]

desc "Steep check lib"
task :steep do
  sh "bundle exec steep check"
end

desc "Steep check exe/cli"
task :steep_cli do
  FileUtils.cd "exe" do
    sh "bundle exec steep check"
  end
end
